import { MomentType, EmotionType, Priority, LanguageDictionary } from './types';
import { GraduationCap, Plane, Briefcase, Heart, Target, Smile, Meh, Frown, Zap, AlertCircle } from 'lucide-react';

export const CATEGORY_CONFIG = {
  [MomentType.STUDY]: { color: 'bg-violet-500', text: 'bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-300', icon: GraduationCap },
  [MomentType.TRAVEL]: { color: 'bg-sky-500', text: 'bg-sky-100 dark:bg-sky-900/30 text-sky-600 dark:text-sky-300', icon: Plane },
  [MomentType.WORK]: { color: 'bg-slate-500', text: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300', icon: Briefcase },
  [MomentType.PERSONAL]: { color: 'bg-pink-500', text: 'bg-pink-100 dark:bg-pink-900/30 text-pink-600 dark:text-pink-300', icon: Heart },
  [MomentType.GOAL]: { color: 'bg-emerald-500', text: 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-300', icon: Target },
};

export const EMOTION_ICONS = {
  [EmotionType.HAPPY]: Smile,
  [EmotionType.NEUTRAL]: Meh,
  [EmotionType.WORRIED]: Frown,
  [EmotionType.EXCITED]: Zap,
  [EmotionType.STRESSED]: AlertCircle,
};

export const TRANSLATIONS: Record<'en' | 'ar', LanguageDictionary> = {
  en: {
    dashboard: 'Dashboard',
    createMoment: 'New Moment',
    memories: 'Memories',
    stats: 'Statistics',
    settings: 'Settings',
    daysLeft: 'Days Left',
    today: 'Today',
    upcoming: 'Upcoming',
    stressLevel: 'Daily Vibe',
    chill: 'Chill',
    balanced: 'Balanced',
    hectic: 'Hectic',
    addMoment: 'Add Moment',
    title: 'Title',
    date: 'Date',
    category: 'Category',
    priority: 'Priority',
    tasks: 'Checklist',
    notes: 'Notes',
    save: 'Save Moment',
    cancel: 'Cancel',
    completed: 'Completed',
    reflection: 'Reflection',
    whatLearned: 'What did you learn?',
    rating: 'Experience Rating',
    repeat: 'Would repeat?',
    yes: 'Yes',
    no: 'No',
    totalMoments: 'Total Moments',
    completionRate: 'Success Rate',
    taskCompletion: 'Task Completion',
    emotionTrend: 'Emotion Trend',
    emotionalJourney: 'Emotional Journey',
    addTask: 'Add Item',
    delete: 'Delete',
    edit: 'Edit',
    days: 'days',
    study: 'Study',
    travel: 'Travel',
    work: 'Work',
    personal: 'Personal',
    goal: 'Goal',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    howFeeling: 'How are you feeling?',
    markAsDone: 'Mark as Done',
    postpone: 'Postpone'
  },
  ar: {
    dashboard: 'الرئيسية',
    createMoment: 'لحظة جديدة',
    memories: 'الذكريات',
    stats: 'الإحصائيات',
    settings: 'الإعدادات',
    daysLeft: 'أيام متبقية',
    today: 'اليوم',
    upcoming: 'القادمة',
    stressLevel: 'مؤشر الهدوء',
    chill: 'هادئ',
    balanced: 'متوازن',
    hectic: 'مضغوط',
    addMoment: 'إضافة لحظة',
    title: 'عنوان اللحظة',
    date: 'التاريخ',
    category: 'التصنيف',
    priority: 'الأهمية',
    tasks: 'المهام',
    notes: 'ملاحظات',
    save: 'حفظ اللحظة',
    cancel: 'إلغاء',
    completed: 'مكتملة',
    reflection: 'تأملات',
    whatLearned: 'ماذا تعلمت؟',
    rating: 'تقييم التجربة',
    repeat: 'هل تكررها؟',
    yes: 'نعم',
    no: 'لا',
    totalMoments: 'إجمالي اللحظات',
    completionRate: 'معدل النجاح',
    taskCompletion: 'إنجاز المهام',
    emotionTrend: 'تطور المشاعر',
    emotionalJourney: 'رحلة المشاعر',
    addTask: 'أضف مهمة',
    delete: 'حذف',
    edit: 'تعديل',
    days: 'أيام',
    study: 'دراسة',
    travel: 'سفر',
    work: 'عمل',
    personal: 'شخصي',
    goal: 'هدف',
    low: 'منخفض',
    medium: 'متوسط',
    high: 'عالي',
    howFeeling: 'كيف تشعر الآن؟',
    markAsDone: 'تم الإنجاز',
    postpone: 'تأجيل'
  }
};